<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ItemsTotal</name>
   <tag></tag>
   <elementGuidId>ec2672cc-e4ad-4017-b5b4-793a436a5345</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-title = 'Subtotal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[data-title=&quot;Subtotal&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Subtotal: $65.00&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>680fd753-cb15-4110-9919-2e16de2e3b81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-title</name>
      <type>Main</type>
      <value>Subtotal</value>
      <webElementGuid>301a7798-5d3a-405a-92e6-068d95b35249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$65.00</value>
      <webElementGuid>d4e1a077-5162-4d34-97fd-d37f9e87fca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-3fe9956a811fd5736989b31c892390df</value>
      <webElementGuid>88c6b41d-3a52-4bc7-95a6-997ee38b3edc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-title = 'Subtotal']</value>
      <webElementGuid>54366dc3-be95-4042-84e3-ec6e4f026299</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-title = 'Subtotal']</value>
      <webElementGuid>e5c6915f-dd44-417f-ab0d-41ea4c5ac5a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '$65.00' or . = '$65.00')]</value>
      <webElementGuid>b172bb45-d05f-4949-9054-6f7e52f21c14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
