<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Logout</name>
   <tag></tag>
   <elementGuidId>d1b72d9d-ec77-4870-87cd-4970adf2e279</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.woocommerce-MyAccount-navigation-link--customer-logout a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' woocommerce-MyAccount-navigation-link--customer-logout ')]//a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Logout&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9c1bcd23-a221-4f78-9f72-fb9c5740dabb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://cms.demo.katalon.com/my-account/customer-logout/?_wpnonce=d67ef89df9</value>
      <webElementGuid>82a62640-ef6e-47eb-80b3-43cffe32449a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>9f35616c-8877-4166-8d13-34bccd12744d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-4b8be05e34af72066275580d7dcda364</value>
      <webElementGuid>e11c8688-040f-4135-a35e-f898d783be0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' woocommerce-MyAccount-navigation-link--customer-logout ')]//a</value>
      <webElementGuid>5b958b6b-985f-4448-b1b8-d503eaabac6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' woocommerce-MyAccount-navigation-link--customer-logout ')]//a</value>
      <webElementGuid>2101015b-7b1f-4dc5-b2d7-e6c7b7724714</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://cms.demo.katalon.com/my-account/customer-logout/?_wpnonce=d67ef89df9' and (text() = 'Logout' or . = 'Logout')]</value>
      <webElementGuid>8ecd7211-0060-409f-bb04-195afe5e69b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
