<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last name_</name>
   <tag></tag>
   <elementGuidId>9c641276-e41f-48d1-a339-53dfdc3c3ce4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'billing_last_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#billing_last_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Last name *&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bf985761-ac77-42dd-a42d-f92428b882b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>53d68f9c-f2f6-403f-bdd3-2f01a8cc6ebd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text </value>
      <webElementGuid>79171c58-c59b-43dc-a0b7-8c77e1ca34d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billing_last_name</value>
      <webElementGuid>a6a96021-2bbd-49a5-a840-9d3c30e29e0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billing_last_name</value>
      <webElementGuid>7f12dcde-09fb-45e7-ae35-f780ecff33c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>customer</value>
      <webElementGuid>18c0ebaa-a87c-4589-a1b0-4ac1df08a3a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>family-name</value>
      <webElementGuid>2f928b06-22ff-4971-8961-9a6dfdbb582a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-a46c2b3e2c1683be61dc43a45c1cb898</value>
      <webElementGuid>69466c52-7899-4886-9f92-64af2c85c831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'billing_last_name']</value>
      <webElementGuid>b45cb589-3b7c-44a5-b7a0-2a4b538f755d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'billing_last_name']</value>
      <webElementGuid>88bb8c00-0a3d-4ac5-a94f-ce55cbad4189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'billing_last_name' and @id = 'billing_last_name']</value>
      <webElementGuid>50d89ba2-a806-432c-8b2c-0838709ff6c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
