<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Add Flying Ninja to your cart</name>
   <tag></tag>
   <elementGuidId>a1af5669-1b71-42a7-88fb-61067330d867</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[aria-label=&quot;Add\ “Flying\ Ninja”\ to\ your\ cart&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@aria-label = 'Add “Flying Ninja” to your cart']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Add “Flying Ninja” to your cart&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7c1c55e1-7b66-4182-872e-93f75499ce97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>?add-to-cart=54</value>
      <webElementGuid>b671f386-402c-4d3a-8d7d-40825d4f38c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-quantity</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>af660808-2d53-4c05-8aa2-75435ba232e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button product_type_simple add_to_cart_button ajax_add_to_cart</value>
      <webElementGuid>44fb98bc-541e-42c3-82c1-5e492490e0cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-product_id</name>
      <type>Main</type>
      <value>54</value>
      <webElementGuid>37457dea-1fda-4402-99db-9436893a57f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-product_sku</name>
      <type>Main</type>
      <value>POSTER-FLYING-NINJA</value>
      <webElementGuid>804a6bc9-654c-478a-ac72-57959f4f0690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Add “Flying Ninja” to your cart</value>
      <webElementGuid>f93d1169-2f27-4224-811e-2ccfa337a4de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>nofollow</value>
      <webElementGuid>450b6dd6-002c-4e6b-ab3a-8f2d48c59ec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add to cart</value>
      <webElementGuid>5b95aecd-d69b-4fcc-8b4d-ba6d4d0abca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-03753b6892fc45243b1fe749292c5383</value>
      <webElementGuid>0a766e76-4c7d-4c8b-9e37-2cbbfeb6d83c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-label = 'Add “Flying Ninja” to your cart']</value>
      <webElementGuid>c03fc607-3f37-477c-a852-489f84eedd0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-label = 'Add “Flying Ninja” to your cart']</value>
      <webElementGuid>14c49bfa-4daf-4d3e-a5c2-66e6900a13e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '?add-to-cart=54' and (text() = 'Add to cart' or . = 'Add to cart')]</value>
      <webElementGuid>8eb673d7-7894-4f14-ad0c-3d26722e2d1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
