<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Add Happy Ninja to your cart</name>
   <tag></tag>
   <elementGuidId>d851dceb-10ac-4e10-b999-b67cd8a3816f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-product_sku=&quot;T-SHIRT-HAPPY-NINJA&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-product_sku = 'T-SHIRT-HAPPY-NINJA']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>li >> internal:has-text=&quot;Add to cart Happy Ninja $18.00&quot;i >> internal:label=&quot;Add “Happy Ninja” to your cart&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>71dd134a-eb04-4702-ab78-f930cd87545c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>?add-to-cart=26</value>
      <webElementGuid>f0d90817-8712-43db-96d8-c1ff3c46b650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-quantity</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5dd50716-5b6e-4dc3-a541-b6825bedd07d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button product_type_simple add_to_cart_button ajax_add_to_cart</value>
      <webElementGuid>fa0e0af3-3959-483d-b89f-806c3c929eb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-product_id</name>
      <type>Main</type>
      <value>26</value>
      <webElementGuid>7a43e21d-f64a-4699-bf54-7988832351a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-product_sku</name>
      <type>Main</type>
      <value>T-SHIRT-HAPPY-NINJA</value>
      <webElementGuid>785873fc-6d9c-4b31-85f3-a4217f7241cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Add “Happy Ninja” to your cart</value>
      <webElementGuid>71e8bdb6-6d5e-4cfa-a5ac-f0bc99c6c0a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>nofollow</value>
      <webElementGuid>d82bf6b6-50cd-4be9-8d7f-7fb8c21421bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add to cart</value>
      <webElementGuid>6bc854d2-dcf1-4eaa-894b-0410851b458c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-063e9c296e1132976bebd77fc2f1ceef</value>
      <webElementGuid>a7e769d3-c456-40f7-9a5c-c92f8e509344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-product_sku = 'T-SHIRT-HAPPY-NINJA']</value>
      <webElementGuid>f9a46373-e7be-4dbc-9c86-3485ad558c83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-product_sku = 'T-SHIRT-HAPPY-NINJA']</value>
      <webElementGuid>09d8e3ad-2f74-4e22-9e37-4df617a0fbe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '?add-to-cart=26' and (text() = 'Add to cart' or . = 'Add to cart')]</value>
      <webElementGuid>0f3d964b-e273-42c6-a8e1-e2ad60c9203e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
