<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Add Happy Ninja to your cart_1</name>
   <tag></tag>
   <elementGuidId>29ec0ccf-7a49-4fb2-988a-f75bb5dc418f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-product_sku=&quot;HOODIE-HAPPY-NINJA&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-product_sku = 'HOODIE-HAPPY-NINJA']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>li >> internal:has-text=&quot;Add to cart Happy Ninja $35.00&quot;i >> internal:label=&quot;Add “Happy Ninja” to your cart&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>908837cc-b437-4cf1-9fba-186649c139cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>?add-to-cart=27</value>
      <webElementGuid>d4a04858-88f1-4008-a0ce-402bea85a92d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-quantity</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>18f11667-7bfa-45e0-af84-62b1d00fc858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button product_type_simple add_to_cart_button ajax_add_to_cart</value>
      <webElementGuid>a773d71d-978c-43e7-ab35-47b781cde5c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-product_id</name>
      <type>Main</type>
      <value>27</value>
      <webElementGuid>758efaf5-a8ec-4d1a-9f24-00299731e63b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-product_sku</name>
      <type>Main</type>
      <value>HOODIE-HAPPY-NINJA</value>
      <webElementGuid>4088118e-08c8-472d-867d-ff4476b176cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Add “Happy Ninja” to your cart</value>
      <webElementGuid>69aaac88-e61d-435d-b011-423eb929e5d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>nofollow</value>
      <webElementGuid>cab1627d-c4fe-46f8-a3e3-2bdfc2b51036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add to cart</value>
      <webElementGuid>388acf69-03b2-4ba2-94ce-caee853a5cd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-3ac6f315708843dccd47582627280276</value>
      <webElementGuid>ae45940b-f75d-4d13-ad00-1d60bb6c92ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-product_sku = 'HOODIE-HAPPY-NINJA']</value>
      <webElementGuid>2ac85d28-7c65-4b00-b0d6-a6e9bcee3fc4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-product_sku = 'HOODIE-HAPPY-NINJA']</value>
      <webElementGuid>c5a78c49-856f-44b9-bb95-fd225199385e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '?add-to-cart=27' and (text() = 'Add to cart' or . = 'Add to cart')]</value>
      <webElementGuid>67335bc3-c41a-4cd9-89a3-9d7b4767081e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
