<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cart</name>
   <tag></tag>
   <elementGuidId>35b9757e-2c5e-406b-9680-da9127667fa5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.page_item:nth-child(1) [href=&quot;https\:\/\/cms\.demo\.katalon\.com\/cart\/&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' page_item ') and (position() = 1)]//*[@href = 'https://cms.demo.katalon.com/cart/']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Cart&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7ac6a983-b1a1-40fe-9f05-ae883b1db519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://cms.demo.katalon.com/cart/</value>
      <webElementGuid>174b395c-a59f-4bd5-aed5-60e559ff1a4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cart</value>
      <webElementGuid>331ea490-b5d5-41df-9e4d-8a292d1e39b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-97d24f24ce62d92897daef7f1fce6427</value>
      <webElementGuid>e6d0f1b5-5f0a-4ea6-92bb-836e637da4aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' page_item ') and (position() = 1)]//*[@href = 'https://cms.demo.katalon.com/cart/']</value>
      <webElementGuid>7bc0c555-0444-4728-9a62-f83af95d18fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' page_item ') and (position() = 1)]//*[@href = 'https://cms.demo.katalon.com/cart/']</value>
      <webElementGuid>379c9e19-b9fd-4fb8-9f68-30d7bf2380ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://cms.demo.katalon.com/cart/' and (text() = 'Cart' or . = 'Cart')]</value>
      <webElementGuid>67730b16-51ad-41fc-a02a-ac91ec0cf248</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
